set -g mouse on

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set -g default-terminal "tmux-256color"
set -sa terminal-features ",*:RGB"
set -as terminal-features ",*:extkeys"

# Soporte para teclas modificadas (Alt, Ctrl, Shift...)
set -s extended-keys on

# Redimensionar panes con Shift + Alt + flechas
bind-key -n M-S-Up resize-pane -U 2
bind-key -n M-S-Down resize-pane -D 2
bind-key -n M-S-Left resize-pane -L 5
bind-key -n M-S-Right resize-pane -R 5
